=== xgdsmileboy/jrrt/tests/rtxf.dtd
<!-- RTXF: refactoring test exchange format -->
<!ELEMENT testsuite (testcase)*>
<!ATTLIST testsuite name CDATA #REQUIRED>

<!ELEMENT testcase (refactoring, program, result)>
<!ATTLIST testcase name CDATA #REQUIRED
	           comment CDATA "">

<!ELEMENT refactoring (extract_block|extract_class|extract_constant|rename)>

<!ELEMENT extract_block (stmtref, stmtref)>

<!ELEMENT extract_class (typeref)>
<!ATTLIST extract_class classname CDATA #REQUIRED
	                fieldname CDATA #REQUIRED
	                fields    NMTOKENS #REQUIRED
	                encapsulate (yes | no) "yes"
	                toplevel  (yes | no) "no">

<!ELEMENT extract_constant (expref)>
<!ATTLIST extract_constant name CDATA #REQUIRED>

<!ELEMENT rename (pkgref | typeref | methodref | fieldref | tempref)>
<!ATTLIST rename newname CDATA #REQUIRED>

<!ELEMENT pkgref EMPTY>
<!ATTLIST pkgref name CDATA #REQUIRED>

<!ELEMENT typeref EMPTY>
<!ATTLIST typeref name CDATA #REQUIRED>
                  
<!ELEMENT methodref EMPTY>
<!ATTLIST methodref host CDATA #REQUIRED
                    signature CDATA #REQUIRED>

<!ELEMENT fieldref EMPTY>
<!ATTLIST fieldref host CDATA #REQUIRED
	           name CDATA #REQUIRED>

<!ELEMENT tempref EMPTY>
<!ATTLIST tempref host CDATA #REQUIRED
	          name CDATA #REQUIRED>

<!ELEMENT stmtref EMPTY>
<!ATTLIST stmtref after CDATA #IMPLIED
	          before CDATA #IMPLIED>

<!ELEMENT expref EMPTY>
<!ATTLIST expref after CDATA "/*[*/"
	         before CDATA "/*]*/">

<!ELEMENT program (cu+ | typedecl+ | bodydecl+ | stmt+)>
<!ELEMENT cu (#PCDATA)>
<!ELEMENT typedecl (#PCDATA)>
<!ELEMENT bodydecl (#PCDATA)>
<!ELEMENT stmt (#PCDATA)>
<!ATTLIST cu name CDATA #REQUIRED>

<!ELEMENT result (program)*>
<!ATTLIST result mayfail (yes | no) "no">

=== xgdsmileboy/jrrt/trunk/tests/ExtractClass.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE testsuite SYSTEM "rtxf.dtd">
<?xml-stylesheet href="rtxf.xsl" type="text/xsl"?>
<testsuite name="Extract Block">
<testcase name="test1">
  <refactoring>
    <extract_class classname="Data" fieldname="data" fields="x y" encapsulate="yes" toplevel="no">
      <typeref name="p.A"/>
    </extract_class>
  </refactoring>
  <program>
    <cu name="p/A.java">
package p;

public class A extends B  {
  int x = init();
  Data y = new Data();
  public int init() {
    return 4 + data;
  }
  public void f() {
    int data;
    x = 0;
    y = new Data();
    this.x = 2;
    this.y.z = 3;
  }
  public void g() {
    Data data;
  }
}

class B  {
  int data = 0;
}

class Data  {
  int z;
}
    </cu>
  </program>
  <result>
    <program>
      <cu name="p/A.java">
package p;

public class A extends B  {
  Data data = new Data();
  {
    data.setX(init());
    data.setY(new p.Data());
  }
  public int init() {
    return 4 + super.data;
  }
  public void f() {
    int data;
    this.data.setX(0);
    this.data.setY(new p.Data());
    this.data.setX(2);
    this.data.getY().z = 3;
  }
  public void g() {
    p.Data data;
  }
  
  static class Data  {
    private int x;
    private p.Data y;
    Data() { }
    Data(int x, p.Data y) {
      this.setX(x);
      this.setY(y);
    }
    int getX() {
      return x;
    }
    int setX(int x) {
      return this.x = x;
    }
    p.Data getY() {
      return y;
    }
    p.Data setY(p.Data y) {
      return this.y = y;
    }
  }
}

class B  {
  int data = 0;
}

class Data  {
  int z;
}
      </cu>
    </program>
  </result>
</testcase>
<testcase name="test2">
  <refactoring>
    <extract_class classname="Data" fieldname="d" fields="x" encapsulate="yes" toplevel="no">
      <typeref name="p.A"/>
    </extract_class>
  </refactoring>
  <program>
    <cu name="p/A.java">
package p;

public class A extends B  {
  int x = init();
  public int init() {
    return 4 + d;
  }
}

class B  {
  int d = 0;
}
    </cu>
  </program>
  <result>
    <program>
      <cu name="p/A.java">
package p;

public class A extends B  {
  Data d = new Data(init());
  public int init() {
    return 4 + super.d;
  }
  
  static class Data  {
    private int x;
    Data() { }
    Data(int x) {
      this.setX(x);
    }
    int getX() {
      return x;
    }
    int setX(int x) {
      return this.x = x;
    }
  }
}

class B  {
  int d = 0;
}
      </cu>
    </program>
  </result>
</testcase>
<testcase name="test3">
  <refactoring>
    <extract_class classname="Data" fieldname="data" fields="x" encapsulate="yes" toplevel="no">
      <typeref name="p.A"/>
    </extract_class>
  </refactoring>
  <program>
    <cu name="p/A.java">
package p;

public class A  {
  Data x;
}

class Data  {
}
    </cu>
  </program>
  <result>
    <program>
      <cu name="p/A.java">
package p;

public class A  {
  Data data = new Data();
  
  static class Data  {
    private p.Data x;
    Data() { }
    Data(p.Data x) {
      this.setX(x);
    }
    p.Data getX() {
      return x;
    }
    p.Data setX(p.Data x) {
      return this.x = x;
    }
  }
}

class Data  {
}
      </cu>
    </program>
  </result>
</testcase>
<testcase name="test4">
  <refactoring>
    <extract_class classname="Data" fieldname="java" fields="x y" encapsulate="yes" toplevel="no">
      <typeref name="p.A"/>
    </extract_class>
  </refactoring>
  <program>
    <cu name="p/A.java">
package p;

class A  {
  int x;
  int y;
  {
    java.lang.System.out.println();
  }
}
    </cu>
  </program>
  <result>
    <program>
      <cu name="p/A.java">
package p;

class A  {
  Data java = new Data();
  {
    System.out.println();
  }
  
  static class Data  {
    private int x;
    private int y;
    Data() { }
    Data(int x, int y) {
      this.setX(x);
      this.setY(y);
    }
    int getX() {
      return x;
    }
    int getY() {
      return y;
    }
    int setX(int x) {
      return this.x = x;
    }
    int setY(int y) {
      return this.y = y;
    }
  }
}
      </cu>
    </program>
  </result>
</testcase>
<testcase name="test5">
  <refactoring>
    <extract_class classname="Data" fieldname="data" fields="x y" encapsulate="yes" toplevel="no">
      <typeref name="p.A"/>
    </extract_class>
  </refactoring>
  <program>
    <cu name="p/A.java">
package p;

class A extends Super  {
  int x = f();
  int y = x + 19;
}

class Super  {
  int f() {
    return 23;
  }
}
    </cu>
  </program>
  <result>
    <program>
      <cu name="p/A.java">
package p;

class A extends Super  {
  static class Data {
    private int x, y;

    Data() { }
    Data(int x, int y) {
      this.setX(x);
      this.setY(y);
    }

    int getX() { return x; }
    int getY() { return y; }
    int setX(int x) { return this.x = x; }
    int setY(int y) { return this.y = y; }
  }

  Data data = new Data();
  {
    data.setX(f());
    data.setY(data.getX() + 19);
  }
}

class Super  {
  int f() {
    return 23;
  }
}
    </cu>
  </program>
  </result>
</testcase>
<testcase name="test6">
  <refactoring>
    <extract_class classname="Data" fieldname="data" fields="x y" encapsulate="yes" toplevel="no">
      <typeref name="p.A"/>
    </extract_class>
  </refactoring>
  <program>
    <cu name="p/A.java">
package p;

class A extends Super  {
  int x = 12;
  int y = x + 19;
}

class Super  {
  int f() {
    return 23;
  }
}
    </cu>
  </program>
  <result>
    <program>
      <cu name="p/A.java">
package p;

class A extends Super  {
  Data data = new Data();
  {
    data.setX(12);
    data.setY(data.getX() + 19);
  }
  
  static class Data  {
    private int x;
    private int y;
    Data() { }
    Data(int x, int y) {
      this.setX(x);
      this.setY(y);
    }
    int getX() {
      return x;
    }
    int getY() {
      return y;
    }
    int setX(int x) {
      return this.x = x;
    }
    int setY(int y) {
      return this.y = y;
    }
  }
}

class Super  {
  int f() {
    return 23;
  }
}
      </cu>
    </program>
  </result>
</testcase>
<testcase name="test7">
  <refactoring>
    <extract_class classname="Data" fieldname="data" fields="x y" encapsulate="yes" toplevel="no">
      <typeref name="p.A"/>
    </extract_class>
  </refactoring>
  <program>
    <cu name="p/A.java">
package p;

class A  {
  int x = 10;
  int z = 20;
  int y = 30;
  {
    java.lang.System.out.println();
  }
}
    </cu>
  </program>
  <result>
    <program>
      <cu name="p/A.java">
package p;

class A  {
  Data data = new Data(10, 30);
  int z = 20;
  {
    java.lang.System.out.println();
  }
  
  static class Data  {
    private int x;
    private int y;
    Data() { }
    Data(int x, int y) {
      this.setX(x);
      this.setY(y);
    }
    int getX() {
      return x;
    }
    int getY() {
      return y;
    }
    int setX(int x) {
      return this.x = x;
    }
    int setY(int y) {
      return this.y = y;
    }
  }
}
      </cu>
    </program>
  </result>
</testcase>
<testcase name="test8">
  <refactoring>
    <extract_class classname="Data" fieldname="data" fields="x y" encapsulate="no" toplevel="no">
      <typeref name="p.A"/>
    </extract_class>
  </refactoring>
  <program>
    <cu name="p/A.java">
package p;

class A  {
  int x = 10;
  int z = 20;
  int y = z;
  {
    java.lang.System.out.println();
  }
}
    </cu>
  </program>
  <result>
    <program>
      <cu name="p/A.java">
package p;

class A  {
  Data data = new Data();
  {
    data.x = 10;
  }
  int z = 20;
  {
    data.y = z;
  }
  {
    java.lang.System.out.println();
  }
  
  static class Data  {
    int x;
    int y;
  }
}
      </cu>
    </program>
  </result>
</testcase>
<testcase name="test9">
  <refactoring>
    <extract_class classname="Data" fieldname="data" fields="x w ww y" encapsulate="yes" toplevel="no">
      <typeref name="p.A"/>
    </extract_class>
  </refactoring>
  <program>
    <cu name="p/A.java">
package p;

class A  {
  int x = 10;
  int z = 20;
  int w;
  java.util.List&lt;Object> ww;
  double y;
  {
    java.lang.System.out.println();
  }
}
    </cu>
  </program>
  <result>
    <program>
      <cu name="p/A.java">
package p;

class A  {
  Data data = new Data(10, 0, null, 0);
  int z = 20;
  {
    java.lang.System.out.println();
  }
  
  static class Data  {
    private int x;
    private int w;
    private java.util.List&lt;Object> ww;
    private double y;
    Data() { }
    Data(int x, int w, java.util.List&lt;Object> ww, double y) {
      this.setX(x);
      this.setW(w);
      this.setWw(ww);
      this.setY(y);
    }
    double getY() {
      return y;
    }
    double setY(double y) {
      return this.y = y;
    }
    int getW() {
      return w;
    }
    int getX() {
      return x;
    }
    int setW(int w) {
      return this.w = w;
    }
    int setX(int x) {
      return this.x = x;
    }
    java.util.List&lt;Object> getWw() {
      return ww;
    }
    java.util.List&lt;Object> setWw(java.util.List&lt;Object> ww) {
      return this.ww = ww;
    }
  }
}
      </cu>
    </program>
  </result>
</testcase>
</testsuite>

=== xgdsmileboy/jrrt/trunk/tests/ExtractBlock.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE testsuite SYSTEM "rtxf.dtd">
<?xml-stylesheet href="rtxf.xsl" type="text/xsl"?>
<testsuite name="Extract Block">
<testcase name="test1">
  <refactoring>
    <extract_block>
      <stmtref after="/*[*/"/>
      <stmtref before="/*]*/"/>
    </extract_block>
  </refactoring>
  <program>
    <cu name="Test.java">
class A  {
  void m() {
    int i;
    /*[*/i = 23;/*]*/
    System.out.println(i);
  }
}
    </cu>
  </program>
  <result>
    <program>
      <cu name="Test.java">
class A  {
  void m() {
    int i;
    {
      /*[*/i = 23;/*]*/
    }
    System.out.println(i);
  }
}
      </cu>
    </program>
  </result>
</testcase>
<testcase name="test2">
  <refactoring>
    <extract_block>
      <stmtref after="/*[*/"/>
      <stmtref before="/*]*/"/>
    </extract_block>
  </refactoring>
  <program>
    <cu name="Test.java">
class A  {
  void m() {
    int i;
    /*[*/i = 23;/*]*/
  }
}
    </cu>
  </program>
  <result>
    <program>
      <cu name="Test.java">
class A  {
  void m() {
    int i;
    {
      /*[*/i = 23;/*]*/
    }
  }
}
      </cu>
    </program>
  </result>
</testcase>
<testcase name="test3">
  <refactoring>
    <extract_block>
      <stmtref after="/*[*/"/>
      <stmtref before="/*]*/"/>
    </extract_block>
  </refactoring>
  <program>
    <cu name="Test.java">
class A  {
  void m() {
    /*[*/int i;
    i = 23;/*]*/
  }
}
    </cu>
  </program>
  <result>
    <program>
      <cu name="Test.java">
class A  {
  void m() {
    {
      /*[*/int i;
      i = 23;/*]*/
    }
  }
}
      </cu>
    </program>
  </result>
</testcase>
<testcase name="test4">
  <refactoring>
    <extract_block>
      <stmtref after="/*[*/"/>
      <stmtref before="/*]*/"/>
    </extract_block>
  </refactoring>
  <program>
    <cu name="Test.java">
class A  {
  void m() {
    /*[*/int i;
    i = 23;/*]*/
    System.out.println(i);
  }
}
    </cu>
  </program>
  <result>
    <program>
      <cu name="Test.java">
class A  {
  void m() {
    /*[*/int i;
    {
      i = 23;/*]*/
    }
    System.out.println(i);
  }
}
      </cu>
    </program>
  </result>
</testcase>
<testcase name="test5">
  <refactoring>
    <extract_block>
      <stmtref after="/*[*/"/>
      <stmtref before="/*]*/"/>
    </extract_block>
  </refactoring>
  <program>
    <cu name="Test.java">
class A  {
  void m() {
    /*[*/int i = 23;/*]*/
    System.out.println(i);
  }
}
    </cu>
  </program>
  <result>
    <program>
      <cu name="Test.java">
class A  {
  void m() {
    /*[*/int i;
    {
      i = 23;/*]*/
    }
    System.out.println(i);
  }
}
      </cu>
    </program>
  </result>
</testcase>
<testcase name="test6">
  <refactoring>
    <extract_block>
      <stmtref after="/*[*/"/>
      <stmtref before="/*]*/"/>
    </extract_block>
  </refactoring>
  <program>
    <cu name="Test.java">
class A  {
  void m() {
    /*[*/System.out.println(42);
    int i = 23;/*]*/
    System.out.println(i);
  }
}
    </cu>
  </program>
  <result>
    <program>
      <cu name="Test.java">
class A  {
  void m() {
    int i;
    {
      /*[*/System.out.println(42);
      i = 23;/*]*/
    }
    System.out.println(i);
  }
}
      </cu>
    </program>
  </result>
</testcase>
<testcase name="test7">
  <refactoring>
    <extract_block>
      <stmtref after="/*[*/"/>
      <stmtref before="/*]*/"/>
    </extract_block>
  </refactoring>
  <program>
    <cu name="Test.java">
class A  {
  void m() {
    /*[*/System.out.println();
    System.out.println();
    int j;
    j = 42;
    System.out.println(j);
    int i = 23;/*]*/
    System.out.println(i + j);
  }
}
    </cu>
  </program>
  <result>
    <program>
      <cu name="Test.java">
class A  {
  void m() {
    int i;
    int j;
    {
      /*[*/System.out.println();
      System.out.println();
      j = 42;
      System.out.println(j);
      i = 23;/*]*/
    }
    System.out.println(i + j);
  }
}
      </cu>
    </program>
  </result>
</testcase>
<testcase name="test8">
  <refactoring>
    <extract_block>
      <stmtref after="/*[*/"/>
      <stmtref before="/*]*/"/>
    </extract_block>
  </refactoring>
  <program>
    <cu name="Test.java">
class A  {
  void m() {
    switch (42){
      /*[*/case 42:
      System.out.println(&quot;Leibniz was right&quot;);
      break ;/*]*/
    }
  }
}
    </cu>
  </program>
  <result mayfail="yes">
  </result>
</testcase>
<testcase name="test9">
  <refactoring>
    <extract_block>
      <stmtref after="/*[*/"/>
      <stmtref before="/*]*/"/>
    </extract_block>
  </refactoring>
  <program>
    <cu name="Test.java">
class A  {
  void m() {
    switch (42){
      /*[*/case 42:/*]*/
      System.out.println(&quot;Leibniz was right&quot;);
      break ;
    }
  }
}
    </cu>
  </program>
  <result mayfail="yes">
  </result>
</testcase>
<testcase name="test10">
  <refactoring>
    <extract_block>
      <stmtref after="/*[*/"/>
      <stmtref before="/*]*/"/>
    </extract_block>
  </refactoring>
  <program>
    <cu name="Test.java">
class A  {
  void m() {
    switch (42){
      case 42:
      /*[*/System.out.println(&quot;Leibniz was right&quot;);
      break ;/*]*/
    }
  }
}
    </cu>
  </program>
  <result>
    <program>
      <cu name="Test.java">
class A  {
  void m() {
    switch (42){
      case 42:
      {
        /*[*/System.out.println(&quot;Leibniz was right&quot;);
        break ;/*]*/
      }
    }
  }
}
      </cu>
    </program>
  </result>
</testcase>
<testcase name="test11">
  <refactoring>
    <extract_block>
      <stmtref after="/*[*/"/>
      <stmtref before="/*]*/"/>
    </extract_block>
  </refactoring>
  <program>
    <cu name="Test.java">
class A  {
  int x;
  void m() {
    /*[*/x = 1;
    int x = 2;/*]*/
    System.out.println(x);
  }
}
    </cu>
  </program>
  <result>
    <program>
      <cu name="Test.java">
class A  {
  int x;
  void m() {
    int x;
    {
      /*[*/this.x = 1;
      x = 2;/*]*/
    }
    System.out.println(x);
  }
}
      </cu>
    </program>
  </result>
</testcase>
</testsuite>

=== xgdsmileboy/jrrt/trunk/tests/RenamePackage.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE testsuite SYSTEM "rtxf.dtd">
<?xml-stylesheet href="rtxf.xsl" type="text/xsl"?>
<testsuite name="Rename Package">
<testcase name="test1">
  <refactoring>
    <rename newname="q">
      <pkgref name="p"/>
    </rename>
  </refactoring>
  <program>
    <cu name="p/A.java">
package p;

class A  {
}
    </cu>
  </program>
  <result>
    <program>
      <cu name="q/A.java">
package q;

class A  {
}
      </cu>
    </program>
  </result>
</testcase>
<testcase name="test2">
  <refactoring>
    <rename newname="q">
      <pkgref name="p"/>
    </rename>
  </refactoring>
  <program>
    <cu name="p/r/A.java">
package p.r;

class A  {
}
    </cu>
  </program>
  <result>
    <program>
      <cu name="q/r/A.java">
package q.r;

class A  {
}
      </cu>
    </program>
  </result>
</testcase>
<testcase name="test3">
  <refactoring>
    <rename newname="q">
      <pkgref name="p"/>
    </rename>
  </refactoring>
  <program>
    <cu name="p/A.java">
package p;

public class A  {
}
    </cu>
    <cu name="r/B.java">
package r;

class B extends p.A  {
}
    </cu>
  </program>
  <result>
    <program>
      <cu name="q/A.java">
package q;

public class A  {
}
      </cu>
      <cu name="r/B.java">
package r;

class B extends q.A  {
}
      </cu>
    </program>
  </result>
</testcase>
<testcase name="test4">
  <refactoring>
    <rename newname="q">
      <pkgref name="p"/>
    </rename>
  </refactoring>
  <program>
    <cu name="p/A.java">
package p;

public class A  {
}
    </cu>
    <cu name="r/B.java">
package r;
import p.A;

class B extends A  {
}
    </cu>
  </program>
  <result>
    <program>
      <cu name="r/B.java">
package r;
import q.A;

class B extends A  {
}
      </cu>
      <cu name="q/A.java">
package q;

public class A  {
}
      </cu>
    </program>
  </result>
</testcase>
<testcase name="test5">
  <refactoring>
    <rename newname="q.r">
      <pkgref name="p"/>
    </rename>
  </refactoring>
  <program>
    <cu name="p/A.java">
package p;

class A  {
}
    </cu>
  </program>
  <result>
    <program>
      <cu name="q/r/A.java">
package q.r;

class A  {
}
      </cu>
    </program>
  </result>
</testcase>
<testcase name="test6" comment="Fails because package exists.">
  <refactoring>
    <rename newname="q">
      <pkgref name="p"/>
    </rename>
  </refactoring>
  <program>
    <cu name="p/A.java">
package p;

class A  {
}
    </cu>
    <cu name="q/B.java">
package q;

class B  {
}
    </cu>
  </program>
  <result mayfail="yes">
  </result>
</testcase>
<testcase name="test7">
  <refactoring>
    <rename newname="q">
      <pkgref name="p"/>
    </rename>
  </refactoring>
  <program>
    <cu name="q/r/B.java">
package q.r;

class B  {
}
    </cu>
    <cu name="p/A.java">
package p;

class A  {
}
    </cu>
  </program>
  <result mayfail="yes">
  </result>
</testcase>
<testcase name="test8">
  <refactoring>
    <rename newname="q.r">
      <pkgref name="p"/>
    </rename>
  </refactoring>
  <program>
    <cu name="p/A.java">
package p;

class A  {
}
    </cu>
    <cu name="q/B.java">
package q;

class B  {
}
    </cu>
  </program>
  <result>
    <program>
      <cu name="q/r/A.java">
package q.r;

class A  {
}
      </cu>
      <cu name="q/B.java">
package q;

class B  {
}
      </cu>
    </program>
  </result>
</testcase>
<testcase name="test9">
  <refactoring>
    <rename newname="q.r">
      <pkgref name="p"/>
    </rename>
  </refactoring>
  <program>
    <cu name="p/A.java">
package p;

class A  {
}
    </cu>
    <cu name="q/B.java">
package q;

class r  {
}
    </cu>
  </program>
  <result mayfail="yes">
  </result>
</testcase>
<testcase name="test10">
  <refactoring>
    <rename newname="q">
      <pkgref name="p"/>
    </rename>
  </refactoring>
  <program>
    <cu name="r/B.java">
package r;

class B extends p.A  {
}

class q  {
}
    </cu>
    <cu name="p/A.java">
package p;

public class A  {
}
    </cu>
  </program>
  <result mayfail="yes">
  </result>
</testcase>
</testsuite>
